# Generated by Django 3.0.2 on 2020-03-13 16:37

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200312_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=models.ImageField(default='group_avatar.png', upload_to=chat.models.chat_photo, verbose_name='Фото'),
        ),
    ]
