# Generated by Django 3.0.2 on 2020-03-13 16:46

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=models.ImageField(blank=True, default='group_avatar.png', null=True, upload_to=chat.models.chat_photo, verbose_name='Фото'),
        ),
    ]
