# Generated by Django 3.0.2 on 2020-03-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
        ('chat', '0004_auto_20200313_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_list',
            field=models.ManyToManyField(to='friendship.Friend'),
        ),
    ]
