# Generated by Django 3.0.2 on 2020-03-16 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20200316_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_list',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
