# Generated by Django 3.0.9 on 2020-09-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200922_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='ts',
        ),
    ]
