# Generated by Django 3.0.9 on 2020-09-22 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200922_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='ts',
        ),
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 21, 19, 26, 635648)),
        ),
    ]
